spring.datasource.url=jdbc:mysql://localhost:3306/students_db
spring.datasource.username=akash
spring.datasource.password=akash18

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
server.port=8085
